fruits = ["orange", "apple", "pear", "banana", "kiwi", "apple", "banana"]
fruits.count("apple")
fruits.count("strawberry")
fruits.index("banana")
fruits.index("banana", 4)
fruits.reverse()
fruits.append("grape") 
fruits.sort()
fruits.pop()
print(fruits)